// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package member

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID        uuid.UUID
	Title     string
	Capacity  int32
	CreatedAt pgtype.Timestamptz
}

type Enrollment struct {
	MemberID   uuid.UUID
	CourseID   uuid.UUID
	Status     string
	EnrolledAt pgtype.Timestamptz
}

type Member struct {
	ID       uuid.UUID
	Name     string
	Email    string
	JoinedAt pgtype.Timestamptz
}
